### ISSUE TITLE
Git Issue Workflow beschreiben

### ISSUE THREAD

**Issue by FlixFixer** [samirmsallem/KMS-MyCargonaut#3]
# Userstory
Als Entwickler brauchen wir ein einheitliches, dokumentiertes, Vorgehen wie wir mit Git Issues bearbeiten, um produktiv gemeinsam und qualitativ hochwertig Software zu entwickeln.

# Beschreibung

Es soll klar sein wie man arbeitet und wie die Qualitätskontrolle abläuft.

# Lösungsvorschlag
Einrichten einer Seite im Wiki von Git in dem die Abläufe beschrieben werden

**Comment by FlixFixer** [comment]
Im Wiki habe ich eine Seite mit Workflow eingerichtet, diese kann man noch abändern falls jemand etwas auffällt.

**Comment by samirmsallem** [comment]
Gefällt mir sehr gut, habe noch einen letzten Abschnitt eingefügt bzgl. Naming um Issues, Branches trackbar zu machen
